"""add new test field

Revision ID: def42cb144e1
Revises: 5f816a0d54c7
Create Date: 2021-09-18 00:12:48.880308

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'def42cb144e1'
down_revision = '5f816a0d54c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('haha', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_note_haha'), 'note', ['haha'], unique=False)
    op.add_column('user', sa.Column('test', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_user_test'), 'user', ['test'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_test'), table_name='user')
    op.drop_column('user', 'test')
    op.drop_index(op.f('ix_note_haha'), table_name='note')
    op.drop_column('note', 'haha')
    # ### end Alembic commands ###
