"""revert changes

Revision ID: f23d56cdb769
Revises: def42cb144e1
Create Date: 2021-09-18 00:14:25.054308

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f23d56cdb769'
down_revision = 'def42cb144e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('test')
    with op.batch_alter_table('note') as batch_op:
        batch_op.drop_column('haha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', sa.VARCHAR(), nullable=False))
    op.create_index('ix_user_test', 'user', ['test'], unique=False)
    op.add_column('note', sa.Column('haha', sa.VARCHAR(), nullable=False))
    op.create_index('ix_note_haha', 'note', ['haha'], unique=False)
    # ### end Alembic commands ###
